export const inspectionCategories = [
  {
    id: 'documentation',
    title: 'Documentación y Básicos',
    points: [
      'Manual del propietario presente',
      'Carnet de servicios',
      'Tarjeta de circulación coincide con VIN',
      'Poliza de seguro vigente',
      'Juego de llaves principal',
      'Juego de llaves duplicado',
      'Control remoto funciona (apertura/cierre)',
      'Botón de pánico funciona',
      'Llave de tuercas de seguridad (si aplica)',
      'Extintor vigente',
      'Triángulos de seguridad',
      'Gato y herramienta básica',
      'Llanta de refacción (presión y estado)'
    ]
  },
  {
    id: 'exterior',
    title: 'Exterior y Carrocería',
    points: [
      'Parachoques delantero (ajuste y pintura)',
      'Parrilla frontal',
      'Cofre (alineación y cierre)',
      'Salpicadera delantera izquierda',
      'Puerta delantera izquierda',
      'Puerta trasera izquierda',
      'Panel lateral trasero izquierdo',
      'Cajuela / Compuerta trasera (alineación y cierre)',
      'Parachoques trasero',
      'Panel lateral trasero derecho',
      'Puerta trasera derecha',
      'Puerta delantera derecha',
      'Salpicadera delantera derecha',
      'Techo y rieles',
      'Espejo lateral izquierdo (carcasa y vidrio)',
      'Espejo lateral derecho (carcasa y vidrio)',
      'Parabrisas (sin estrelladuras)',
      'Medallón trasero',
      'Cristales de puertas (suben y bajan)',
      'Limpiaparabrisas (gomas y funcionamiento)',
      'Faros principales (altas y bajas)',
      'Luces de niebla',
      'Direccionales delanteras',
      'Direccionales traseras',
      'Luces de freno',
      'Tercera luz de freno',
      'Luces de reversa',
      'Luces de placa',
      'Tapón de gasolina (cierre correcto)'
    ]
  },
  {
    id: 'interior',
    title: 'Interior y Confort',
    points: [
      'Asiento conductor (ajuste y estado)',
      'Asiento pasajero (ajuste y estado)',
      'Asientos traseros',
      'Cinturones de seguridad (funcionamiento y estado)',
      'Bolsas de aire (testigo en tablero)',
      'Alfombras y tapetes',
      'Cielo raso (techo interior)',
      'Tablero (sin grietas)',
      'Volante (desgaste y botones)',
      'Claxon',
      'Espejo retrovisor central',
      'Viseras y espejos de vanidad',
      'Luces interiores (lectura y cortesía)',
      'Panel de instrumentos (iluminación)',
      'Testigos de advertencia (check engine, abs, etc.)',
      'Sistema de aire acondicionado (frío)',
      'Calefacción',
      'Desempañador trasero',
      'Sistema de audio (radio, bluetooth, bocinas)',
      'Pantalla táctil / Infoentretenimiento',
      'Cámara de reversa',
      'Sensores de estacionamiento',
      'Puertos USB y tomas de 12V',
      'Ventanas eléctricas (botones y operación)',
      'Seguros eléctricos',
      'Manijas interiores',
      'Freno de mano (palanca o botón)',
      'Pedales (gomas y recorrido)'
    ]
  },
  {
    id: 'engine',
    title: 'Motor y Bajo el Cofre',
    points: [
      'Nivel de aceite de motor',
      'Condición del aceite de motor',
      'Nivel de anticongelante',
      'Condición del anticongelante',
      'Nivel de líquido de frenos',
      'Nivel de dirección hidráulica (si aplica)',
      'Líquido limpiaparabrisas',
      'Batería (fijación y terminales)',
      'Prueba de carga de batería',
      'Filtro de aire (inspección visual)',
      'Bandas de accesorios (desgaste y tensión)',
      'Mangueras de radiador y calefacción',
      'Fugas de aceite visibles (tapa de punterías)',
      'Fugas de refrigerante visibles',
      'Ruidos anormales en ralentí',
      'Soportes de motor (vibración)',
      'Cableado del motor (estado general)',
      'Amortiguadores de cofre'
    ]
  },
  {
    id: 'undercarriage',
    title: 'Chasis y Bajos',
    points: [
      'Amortiguadores delanteros (fugas)',
      'Amortiguadores traseros (fugas)',
      'Bujes de suspensión',
      'Rótulas',
      'Flechas y cubrepolvos (homocinéticas)',
      'Caja de dirección (fugas y juego)',
      'Sistema de escape (fugas y fijación)',
      'Convertidor catalítico',
      'Tanque de combustible y líneas',
      'Chasis / Largueros (daño estructural u óxido)',
      'Piso de la carrocería',
      'Fugas de transmisión',
      'Fugas de diferencial (si aplica)'
    ]
  },
  {
    id: 'brakes_tires',
    title: 'Frenos, Llantas y Rines',
    points: [
      'Llanta Delantera Izquierda (profundidad dibujo)',
      'Llanta Delantera Izquierda (desgaste irregular)',
      'Llanta Delantera Derecha (profundidad dibujo)',
      'Llanta Delantera Derecha (desgaste irregular)',
      'Llanta Trasera Izquierda (profundidad dibujo)',
      'Llanta Trasera Izquierda (desgaste irregular)',
      'Llanta Trasera Derecha (profundidad dibujo)',
      'Llanta Trasera Derecha (desgaste irregular)',
      'Presión de llantas correcta',
      'Rines (golpes o deformaciones)',
      'Balatas delanteras (% vida)',
      'Discos delanteros (ceja o cristalización)',
      'Balatas traseras (% vida)',
      'Discos/Tambores traseros',
      'Líneas y mangueras de freno'
    ]
  },
  {
    id: 'test_drive',
    title: 'Prueba de Manejo',
    points: [
      'Arranque en frío',
      'Ralentí estable',
      'Respuesta de aceleración',
      'Potencia del motor',
      'Cambios de transmisión (suaves y a tiempo)',
      'Funcionamiento en modo manual/sport',
      'Alineación de dirección (vehículo se va de lado)',
      'Vibraciones al volante',
      'Ruidos de suspensión al pasar baches',
      'Ruidos de baleros de rueda',
      'Eficiencia de frenado',
      'Vibración al frenar',
      'Funcionamiento del ABS (si condiciones permiten)',
      'Control de crucero',
      'Puntos ciegos y visibilidad',
      'Olores extraños tras la prueba'
    ]
  }
];
